# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Render Newton validation rollouts and the gripper co-design figures.

The workflow diagram (``outputs/gripper/gripper_workflow.svg``) ships as a
static figure and is no longer generated by this script.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import gripper_scene as scene
import numpy as np
import torch
from PIL import Image, ImageDraw, ImageFont

from physicsnemo.experimental.integrations.newton.visualization import (
    aim_camera,
    capture_frame,
    headless_viewer,
    save_gif,
)

HANDLED_CUP_INDEX = next(
    index
    for index, grasp_object in enumerate(scene.OBJECTS)
    if grasp_object.name == "handled_cup"
)
CUP_HANDLE_HORIZONTAL_POSE_INDEX = 1


def _load_data(path: Path) -> dict[str, np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} does not exist; run example_gripper_design.py first"
        )
    data = np.load(path)
    return {key: data[key] for key in data.files}


def _poses_from_data(data: dict[str, np.ndarray]):
    return tuple(
        tuple(scene.GraspPose(*map(float, values)) for values in object_poses)
        for object_poses in data["poses"]
    )


def _label(
    frame: Image.Image,
    labels: list[tuple[str, tuple[int, int]]],
) -> Image.Image:
    image = frame.convert("RGB")
    draw = ImageDraw.Draw(image, "RGBA")
    for text, xy in labels:
        box = draw.textbbox(xy, text)
        draw.rectangle(
            (box[0] - 5, box[1] - 3, box[2] + 5, box[3] + 3),
            fill=(10, 15, 20, 205),
        )
        draw.text(xy, text, fill=(245, 250, 255, 255))
    return image


def _grid(frames: list[Image.Image], columns: int = 2) -> Image.Image:
    if not frames:
        raise ValueError("frames must not be empty")
    rows = (len(frames) + columns - 1) // columns
    width = max(frame.width for frame in frames)
    height = max(frame.height for frame in frames)
    canvas = Image.new("RGB", (columns * width, rows * height), (14, 18, 22))
    for index, frame in enumerate(frames):
        canvas.paste(frame, ((index % columns) * width, (index // columns) * height))
    return canvas


def _presentation_viewer(width: int, height: int):
    """Create a viewer with presentation-oriented material settings."""
    viewer = headless_viewer(width, height)
    # ``_specular_scale`` / ``_exposure`` are Newton-internal renderer knobs with
    # no public API today; guard so a future upstream rename degrades to a no-op
    # (cosmetic tuning is lost) instead of crashing figure generation.
    if hasattr(viewer.renderer, "_specular_scale"):
        viewer.renderer._specular_scale = 0.0
    if hasattr(viewer.renderer, "_exposure"):
        viewer.renderer._exposure = 1.25
    return viewer


def render_pointnet_shape_families(
    data: dict[str, np.ndarray],
    *,
    output: Path,
) -> Path:
    """Visualize the normalized object surface patches consumed by PointNet."""
    import matplotlib.pyplot as plt

    plt.switch_backend("Agg")
    clouds = np.asarray(data["point_clouds"], dtype=np.float32)
    pose_index = 0
    split_rows = (
        (
            "TRAINING FAMILIES",
            tuple(range(8)),
            "#2474b5",
            0.665,
            0.105,
            0.075,
            0.008,
        ),
        (
            "UNSEEN VALIDATION",
            tuple(range(8, 12)),
            "#7d4ca5",
            0.355,
            0.145,
            0.185,
            0.022,
        ),
        (
            "UNTOUCHED TEST",
            (12,),
            "#ef7d32",
            0.055,
            0.165,
            0.245,
            0.0,
        ),
    )
    display_names = {
        "faceted_bottle": "faceted bottle",
        "asymmetric_pear": "asymmetric pear",
        "ribbed_vessel": "ribbed vessel",
        "handled_cup": "handled cup",
        "offset_power_tool": "power tool",
        "organic_lobed_mesh": "organic mesh",
        "twisted_star_mesh": "twisted star",
        "sphere": "sphere",
        "faceted_gem": "faceted gem",
        "unseen_organic_mesh": "unseen organic",
        "forked_household_tool": "forked tool",
        "double_lobed_container": "double-lobed",
        "unseen_asymmetric_bottle": "asymmetric bottle",
    }

    fig = plt.figure(figsize=(18, 9), facecolor="#f7f9fb")
    fig.text(
        0.5,
        0.955,
        "PointNet input shape families",
        ha="center",
        va="center",
        fontsize=24,
        fontweight="bold",
        color="#17212b",
    )
    fig.text(
        0.5,
        0.915,
        "Actual normalized 192-point surface patches used by the surrogate",
        ha="center",
        va="center",
        fontsize=13,
        color="#52606d",
    )

    for label, indices, color, y, width, start_x, gap in split_rows:
        fig.text(
            0.035,
            y + 0.10,
            label,
            ha="center",
            va="center",
            fontsize=11,
            fontweight="bold",
            color=color,
            rotation=90,
        )
        for column, object_index in enumerate(indices):
            x = start_x + column * (width + gap)
            axis = fig.add_axes((x, y, width, 0.20), facecolor="#ffffff")
            points = clouds[object_index, pose_index]
            depth = 0.30 + 0.65 * (points[:, 1] + 1.0) / 2.0
            point_colors = np.empty((len(points), 4), dtype=np.float32)
            rgb = np.asarray(
                tuple(int(color[index : index + 2], 16) / 255.0 for index in (1, 3, 5))
            )
            point_colors[:, :3] = rgb
            point_colors[:, 3] = np.clip(depth, 0.25, 0.95)
            axis.scatter(
                points[:, 0],
                points[:, 2],
                s=8,
                c=point_colors,
                linewidths=0,
            )
            axis.set_xlim(-1.08, 1.08)
            axis.set_ylim(-1.08, 1.08)
            axis.set_aspect("equal")
            axis.set_xticks(())
            axis.set_yticks(())
            for spine in axis.spines.values():
                spine.set_color("#d9e2ec")
                spine.set_linewidth(1.2)
            axis.set_title(
                display_names[scene.OBJECTS[object_index].name],
                fontsize=10.5,
                color="#243b53",
                pad=7,
            )

    fig.text(
        0.49,
        0.150,
        "One PointNet encoder spans every family.",
        fontsize=14,
        fontweight="bold",
        color="#17212b",
    )
    fig.text(
        0.49,
        0.112,
        "Analytic, compound, and mesh-backed objects share one representation.",
        fontsize=11.5,
        color="#52606d",
    )
    fig.text(
        0.49,
        0.075,
        "Validation and test shapes are never used as training targets.",
        fontsize=11.5,
        color="#52606d",
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=160, facecolor=fig.get_facecolor())
    plt.close(fig)
    return output


def _display_pose_index(data: dict[str, np.ndarray], object_index: int) -> int:
    """Show the cup upright with its handle horizontal in the image."""
    if object_index == HANDLED_CUP_INDEX:
        return CUP_HANDLE_HORIZONTAL_POSE_INDEX
    return int(data["selected_pose_indices"][object_index])


def _camera_azimuth(override: float | None) -> float:
    """Return the camera azimuth, defaulting to a fixed 90 degrees."""
    if override is not None:
        return float(override)
    return 90.0


def _single_comparison_clip(
    data: dict[str, np.ndarray],
    *,
    object_index: int,
    design: np.ndarray,
    pose_index: int,
    design_label: str,
    viewer,
    args: argparse.Namespace,
) -> list[Image.Image]:
    poses = _poses_from_data(data)
    options = scene.SimulationOptions(
        fps=args.sim_fps,
        substeps=args.substeps,
        sim_time=args.sim_time,
        solver_iterations=args.solver_iterations,
        disturbance_force=args.disturbance_force,
    )
    batch = scene.build_gripper_batch(
        np.asarray(design, dtype=np.float32)[None],
        np.asarray((object_index,), dtype=np.int64),
        np.asarray((pose_index,), dtype=np.int64),
        poses=poses,
        options=options,
        device=args.device,
    )
    viewer.set_model(batch.model)
    aim_camera(
        viewer,
        np.asarray((-0.20, -0.13, -0.01)),
        np.asarray((0.20, 0.13, 0.56)),
        azim=_camera_azimuth(args.azim),
        elev=args.elev,
        margin=1.06,
    )

    frames: list[Image.Image] = []
    stride = max(1, options.frame_count // args.max_frames)
    time = 0.0
    for frame_index in range(options.frame_count):
        for _ in range(options.substeps):
            time = scene.step_gripper_batch(batch, time)
        if frame_index % stride:
            continue
        viewer.begin_frame(time)
        viewer.log_state(batch.state_0)
        viewer.end_frame()
        frame = capture_frame(viewer)
        frames.append(
            _label(
                frame,
                [(design_label, (12, 10))],
            )
        )
    frames.extend([frames[-1]] * 8)
    return frames


def _comparison_clip(
    data: dict[str, np.ndarray],
    *,
    object_index: int,
    viewer,
    args: argparse.Namespace,
) -> tuple[list[Image.Image], list[Image.Image]]:
    shared_pose_index = _display_pose_index(data, object_index)
    baseline = _single_comparison_clip(
        data,
        object_index=object_index,
        design=scene.baseline_design(),
        pose_index=shared_pose_index,
        design_label="Baseline",
        viewer=viewer,
        args=args,
    )
    refined = _single_comparison_clip(
        data,
        object_index=object_index,
        design=data["best_physical_design"],
        pose_index=shared_pose_index,
        design_label="Optimized",
        viewer=viewer,
        args=args,
    )
    return baseline, refined


def _detail_snapshot(
    data: dict[str, np.ndarray],
    *,
    design: np.ndarray,
    viewer,
    args: argparse.Namespace,
    target_time: float = 0.55,
) -> Image.Image:
    poses = _poses_from_data(data)
    options = scene.SimulationOptions(
        fps=args.sim_fps,
        substeps=args.substeps,
        sim_time=args.sim_time,
        solver_iterations=args.solver_iterations,
        disturbance_force=args.disturbance_force,
    )
    batch = scene.build_gripper_batch(
        np.asarray(design, dtype=np.float32)[None],
        np.asarray((HANDLED_CUP_INDEX,), dtype=np.int64),
        np.asarray((CUP_HANDLE_HORIZONTAL_POSE_INDEX,), dtype=np.int64),
        poses=poses,
        options=options,
        device=args.device,
    )
    viewer.set_model(batch.model)
    aim_camera(
        viewer,
        np.asarray((-0.14, -0.12, 0.01)),
        np.asarray((0.14, 0.12, 0.43)),
        azim=90.0,
        elev=20.0,
        margin=0.94,
    )
    time = 0.0
    while time < target_time:
        time = scene.step_gripper_batch(batch, time)
    viewer.begin_frame(time)
    viewer.log_state(batch.state_0)
    viewer.end_frame()
    return capture_frame(viewer).convert("RGB")


def _load_font(size: int, *, bold: bool = False) -> ImageFont.ImageFont:
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    try:
        return ImageFont.truetype(f"/usr/share/fonts/truetype/dejavu/{name}", size)
    except OSError:
        # DejaVu is not installed everywhere (macOS, RHEL, slim containers);
        # fall back to PIL's bundled bitmap font like the sibling renderers.
        return ImageFont.load_default()


def _parameter_rows(
    baseline: np.ndarray,
    optimized: np.ndarray,
) -> tuple[tuple[str, str, str], ...]:
    def millimeters(value: float) -> str:
        return f"{1000.0 * value:.1f} mm"

    def degrees(value: float) -> str:
        return f"{np.degrees(value):.1f} deg"

    return (
        (
            "Total finger length",
            millimeters(
                float(
                    (
                        baseline[scene.LENGTH_SLICE]
                        * baseline[scene.FINGER_SCALE_INDEX]
                    ).sum()
                )
            ),
            millimeters(
                float(
                    (
                        optimized[scene.LENGTH_SLICE]
                        * optimized[scene.FINGER_SCALE_INDEX]
                    ).sum()
                )
            ),
        ),
        (
            "Palm span",
            millimeters(2.0 * float(baseline[scene.ROOT_HALF_WIDTH_INDEX])),
            millimeters(2.0 * float(optimized[scene.ROOT_HALF_WIDTH_INDEX])),
        ),
        (
            "Base radius",
            millimeters(float(baseline[scene.RADIUS_SLICE][0])),
            millimeters(float(optimized[scene.RADIUS_SLICE][0])),
        ),
        (
            "Middle radius",
            millimeters(float(baseline[scene.RADIUS_SLICE][2])),
            millimeters(float(optimized[scene.RADIUS_SLICE][2])),
        ),
        (
            "Tip radius",
            millimeters(float(baseline[scene.RADIUS_SLICE][-1])),
            millimeters(float(optimized[scene.RADIUS_SLICE][-1])),
        ),
        (
            "Total rest bend",
            degrees(float(baseline[scene.REST_ANGLE_SLICE].sum())),
            degrees(float(optimized[scene.REST_ANGLE_SLICE].sum())),
        ),
        (
            "Pad protrusion",
            millimeters(float(baseline[scene.PAD_PROTRUSION_INDEX])),
            millimeters(float(optimized[scene.PAD_PROTRUSION_INDEX])),
        ),
        (
            "Pad width",
            millimeters(2.0 * float(baseline[scene.PAD_HALF_WIDTH_INDEX])),
            millimeters(2.0 * float(optimized[scene.PAD_HALF_WIDTH_INDEX])),
        ),
    )


def render_design_detail(
    data: dict[str, np.ndarray],
    *,
    output: Path,
    args: argparse.Namespace,
) -> Path:
    """Render a close-up, controlled comparison with a compact parameter table."""
    baseline = scene.baseline_design()
    optimized = np.asarray(data["best_physical_design"], dtype=np.float32)
    viewer = _presentation_viewer(500, 520)
    baseline_image = _detail_snapshot(
        data,
        design=baseline,
        viewer=viewer,
        args=args,
    )
    optimized_image = _detail_snapshot(
        data,
        design=optimized,
        viewer=viewer,
        args=args,
    )

    canvas = Image.new("RGB", (1600, 700), "#f6f8fa")
    draw = ImageDraw.Draw(canvas)
    title_font = _load_font(30, bold=True)
    subtitle_font = _load_font(17)
    heading_font = _load_font(21, bold=True)
    table_font = _load_font(17)
    table_bold = _load_font(17, bold=True)

    draw.text(
        (36, 24),
        "What geometry optimization changed",
        fill="#17212b",
        font=title_font,
    )
    draw.text(
        (36, 65),
        "Shorter, thicker, pre-curved fingers wrap around the handled cup",
        fill="#52606d",
        font=subtitle_font,
    )
    canvas.paste(baseline_image, (28, 132))
    canvas.paste(optimized_image, (536, 132))
    draw.text((210, 103), "Baseline", fill="#17212b", font=heading_font)
    draw.text((700, 103), "Optimized", fill="#17212b", font=heading_font)

    table_x = 1068
    table_y = 112
    table_width = 504
    row_height = 52
    column_x = (table_x + 16, table_x + 282, table_x + 398)
    parameter_rows = _parameter_rows(baseline, optimized)
    draw.rounded_rectangle(
        (
            table_x,
            table_y,
            table_x + table_width,
            table_y + (len(parameter_rows) + 1) * row_height,
        ),
        radius=12,
        fill="#ffffff",
        outline="#cbd2d9",
        width=2,
    )
    draw.rectangle(
        (table_x, table_y, table_x + table_width, table_y + row_height),
        fill="#17212b",
    )
    for x, text in zip(column_x, ("Geometry", "Baseline", "Optimized")):
        draw.text((x, table_y + 15), text, fill="#ffffff", font=table_bold)
    for row_index, (name, base_value, optimized_value) in enumerate(
        parameter_rows, start=1
    ):
        y = table_y + row_index * row_height
        if row_index % 2 == 0:
            draw.rectangle(
                (table_x + 1, y, table_x + table_width - 1, y + row_height),
                fill="#f1f4f7",
            )
        draw.line(
            (table_x, y, table_x + table_width, y),
            fill="#d9e2ec",
            width=1,
        )
        draw.text((column_x[0], y + 15), name, fill="#243b53", font=table_font)
        draw.text(
            (column_x[1], y + 15),
            base_value,
            fill="#52606d",
            font=table_font,
        )
        draw.text(
            (column_x[2], y + 15),
            optimized_value,
            fill="#4d7c0f",
            font=table_bold,
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output)
    return output


def render_comparison(
    data: dict[str, np.ndarray],
    *,
    output: Path,
    args: argparse.Namespace,
) -> Path:
    """Render simple-baseline/co-designed pairs for representative tasks."""
    object_indices = scene.DISPLAY_OBJECT_INDICES
    viewer = _presentation_viewer(args.panel_width // 2, args.panel_height)
    clip_pairs = [
        _comparison_clip(data, object_index=index, viewer=viewer, args=args)
        for index in object_indices
    ]
    length = min(len(clip) for pair in clip_pairs for clip in pair)
    grids = []
    for frame_index in range(length):
        panels = []
        for baseline, refined in clip_pairs:
            panels.extend((baseline[frame_index], refined[frame_index]))
        grids.append(_grid(panels, columns=2))
    save_gif(grids, output, fps=args.gif_fps, palette=True)
    return output


def run(args: argparse.Namespace) -> None:
    """Generate all documented gripper figures and animations."""
    data = _load_data(Path(args.data))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    comparison = render_comparison(
        data,
        output=output_dir / "gripper_before_after.gif",
        args=args,
    )
    detail = render_design_detail(
        data,
        output=output_dir / "gripper_design_detail.png",
        args=args,
    )
    shape_families = render_pointnet_shape_families(
        data,
        output=output_dir / "gripper_pointnet_shape_families.png",
    )
    print(f"wrote {comparison}")
    print(f"wrote {detail}")
    print(f"wrote {shape_families}")


def parse_args() -> argparse.Namespace:
    """Parse gripper rendering options."""
    parser = argparse.ArgumentParser(description="Render Newton gripper co-design")
    example_dir = Path(__file__).parent
    parser.add_argument(
        "--data",
        type=Path,
        default=example_dir / "outputs" / "gripper" / "gripper_design_data.npz",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=example_dir / "outputs" / "gripper",
    )
    parser.add_argument("--panel-width", type=int, default=720)
    parser.add_argument("--panel-height", type=int, default=240)
    parser.add_argument("--gif-fps", type=float, default=18.0)
    parser.add_argument("--max-frames", type=int, default=48)
    parser.add_argument("--sim-time", type=float, default=2.0)
    parser.add_argument("--sim-fps", type=float, default=60.0)
    parser.add_argument("--substeps", type=int, default=8)
    parser.add_argument("--solver-iterations", type=int, default=36)
    parser.add_argument("--disturbance-force", type=float, default=1.6)
    parser.add_argument(
        "--azim",
        type=float,
        default=None,
        help="camera azimuth override in degrees; defaults to a fixed 90 degrees",
    )
    parser.add_argument("--elev", type=float, default=18.0)
    parser.add_argument(
        "--device", default="cuda" if torch.cuda.is_available() else "cpu"
    )
    args = parser.parse_args()
    if args.sim_time * args.sim_fps < 1.0:
        parser.error("--sim-time and --sim-fps must produce at least one frame")
    if args.max_frames <= 0:
        parser.error("--max-frames must be positive")
    return args


if __name__ == "__main__":
    run(parse_args())
