# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Teacher problem definition, dataset, and distributed trajectory collection."""

from __future__ import annotations

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np
import torch

from physicsnemo.experimental.integrations.newton.distributed import (
    _all_reduce,
    _rank_world_size,
    resolve_device,
)
from physicsnemo.experimental.integrations.newton.nerd.codecs import (
    NeRDBodyHeadingFrame,
    NeRDFixedFrame,
    NeRDStateCodec,
    nerd_state_codec,
)
from physicsnemo.experimental.integrations.newton.nerd.runtime import _nerd_log

if TYPE_CHECKING:
    from physicsnemo.experimental.integrations.newton.env import NewtonEnv


@dataclass
class NeRDProblem:
    """One Newton teacher run adapted to NeRD collection.

    Parameters
    ----------
    codec : NeRDStateCodec
        State representation learned by the model.
    get_state : Callable[[], Any]
        Callable returning the current Newton state.
    reset : Callable[[numpy.random.Generator], None]
        Callable that resets or randomizes one batch of worlds.
    advance : Callable[[torch.Tensor, int], None]
        Callable ``advance(inputs, frame)`` that advances exactly one teacher
        frame. ``inputs`` drive the transition from ``state[frame]`` to
        ``state[frame + 1]``, and ``frame`` ranges over ``[0, steps)``.
    sample_inputs : Callable, optional
        Callable ``sample_inputs(rng, batch_size, frame)`` returning global
        per-world features shaped ``[batch_size, features]`` or entity-aligned
        features shaped ``[batch_size, entities, features]``. Omit for
        autonomous dynamics.
    name : str, optional
        Human-readable problem name used in diagnostics.
    environment : Any, optional
        Underlying environment retained for application-specific access.
    frame_dt : float, optional
        Duration of one teacher frame in seconds.
    observe_inputs : Callable, optional
        Callable ``observe_inputs(sampled_inputs, frame)`` invoked at the current
        state before :attr:`advance`. It may read live state, controls, or
        contacts through a closure and must return the exact model features to
        store. When omitted, sampled inputs are stored directly.

    Notes
    -----
    The sampled inputs for frame ``i`` drive the transition to snapshot ``i + 1``.
    Therefore, the collected ``inputs`` tensor always has one fewer frame than
    ``states``.
    """

    codec: NeRDStateCodec
    get_state: Callable[[], Any]
    reset: Callable[[np.random.Generator], None]
    advance: Callable[[torch.Tensor, int], None]
    sample_inputs: Callable[[np.random.Generator, int, int], Any] | None = None
    name: str = "Newton"
    environment: Any | None = None
    frame_dt: float | None = None
    observe_inputs: Callable[[torch.Tensor, int], Any] | None = None

    @property
    def batch_size(self) -> int:
        """Number of trajectories generated by each reset/rollout."""
        return self.codec.batch_size

    @classmethod
    def from_env(
        cls,
        env: NewtonEnv,
        *,
        state_codec: NeRDStateCodec | str | Sequence[str],
        randomize: Callable[[NewtonEnv, np.random.Generator], None] | None = None,
        sample_inputs: Callable[[np.random.Generator, int, int], Any] | None = None,
        apply_inputs: Callable[[NewtonEnv, torch.Tensor, int, int], None] | None = None,
        observe_inputs: Callable[[NewtonEnv, torch.Tensor, int], Any] | None = None,
        joint_robot_centric: bool = True,
        body_reference_frame: NeRDFixedFrame | NeRDBodyHeadingFrame | None = None,
        name: str = "Newton",
    ) -> NeRDProblem:
        """Adapt a standard :class:`NewtonEnv` lifecycle to NeRD.

        ``randomize`` runs after :meth:`NewtonEnv.reset` and only needs to apply
        application-specific domain randomization. Any randomization that changes
        contact geometry must go through the ``randomize`` hook (not a separate
        path) so that contacts are refreshed by the post-randomization collide;
        that refresh only runs when ``env.collide_on_reset`` is set.
        ``apply_inputs`` runs after force clearing before every solver substep,
        so it works for control fields as well as state forces.
        ``observe_inputs`` runs before the teacher frame and may combine sampled
        controls with state-derived features. Contact-conditioned callbacks should
        refresh collision detection before reading contacts; use
        :meth:`NeRDRigidContactInput.read_env` for that common case.
        ``state_codec`` is explicit: pass a ready codec, ``"joint"``,
        ``"body"``, ``"particle"``, or a sequence for a composite state.
        ``joint_robot_centric`` applies only when building a joint codec from a
        representation name. Body codecs remain in world coordinates unless
        ``body_reference_frame`` supplies a fixed-environment or moving-body
        frame. A ready codec owns its frame configuration.
        """
        codec = (
            state_codec
            if isinstance(state_codec, NeRDStateCodec)
            else nerd_state_codec(
                env.model,
                state_codec,
                joint_robot_centric=joint_robot_centric,
                body_reference_frame=body_reference_frame,
            )
        )

        def reset_env(rng: np.random.Generator) -> None:
            env.reset()
            if randomize is not None:
                randomize(env, rng)
                if env.collide_on_reset:
                    env.collide()

        def advance_env(inputs: torch.Tensor, frame: int) -> None:
            before_substep = None
            if apply_inputs is not None:

                def apply_before_substep(
                    state: Any,
                    control: Any,
                    contacts: Any,
                    dt: float,
                    substep: int,
                ) -> None:
                    del state, control, contacts, dt
                    apply_inputs(env, inputs, frame, substep)

                before_substep = apply_before_substep

            env.step(before_substep=before_substep)

        def observe_env(inputs: torch.Tensor, frame: int) -> Any:
            return observe_inputs(env, inputs, frame)

        return cls(
            codec=codec,
            get_state=lambda: env.state,
            reset=reset_env,
            advance=advance_env,
            sample_inputs=sample_inputs,
            observe_inputs=observe_env if observe_inputs is not None else None,
            name=name,
            environment=env,
            frame_dt=env.frame_dt,
        )


@dataclass
class NeRDDataset:
    """Teacher states and inputs collected for a NeRD problem.

    The dataset takes ownership of (does not copy) the provided ``states`` and
    ``inputs`` tensors and detaches them from any caller autograd graph, so
    callers should not mutate them after construction. Omitting ``frame_dt``
    disables deployment-time timestep validation.
    """

    states: torch.Tensor
    codec: NeRDStateCodec
    inputs: torch.Tensor | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    frame_dt: float | None = None

    def __post_init__(self) -> None:
        self.states = self.states.detach()
        expected_ndim = 2 + len(self.codec.state_shape)
        if self.states.ndim != expected_ndim:
            raise ValueError(
                "states must have shape "
                f"[trajectories, frames, *state_shape]; got {tuple(self.states.shape)}"
            )
        if self.states.shape[0] == 0 or self.states.shape[1] < 2:
            raise ValueError(
                "states must contain at least one trajectory and two frames"
            )
        expected_state = (*self.states.shape[:2], *self.codec.state_shape)
        if tuple(self.states.shape) != expected_state:
            raise ValueError(
                f"states must have shape {expected_state}, got {tuple(self.states.shape)}"
            )
        if self.inputs is None:
            self.inputs = self.states.new_empty(
                (self.states.shape[0], self.states.shape[1] - 1, 0)
            )
        else:
            self.inputs = self.inputs.detach()
        if self.inputs.ndim < 3:
            raise ValueError(
                "inputs must have shape [trajectories, frames, *external_input_shape]"
            )
        if self.inputs.shape[:2] != (
            self.states.shape[0],
            self.states.shape[1] - 1,
        ):
            raise ValueError("inputs must contain one frame for every state transition")
        if self.frame_dt is not None and (
            not math.isfinite(self.frame_dt) or self.frame_dt <= 0.0
        ):
            raise ValueError("frame_dt must be finite and positive when provided")

    @property
    def external_input_dim(self) -> int:
        """Final feature width of each global or per-entity input."""
        return int(self.inputs.shape[-1])

    @property
    def external_input_shape(self) -> tuple[int, ...]:
        """Per-frame global or entity-aligned inputs shape."""
        return tuple(self.inputs.shape[2:])


def collect_nerd_trajectories(
    problem: NeRDProblem,
    *,
    num_trajectories: int,
    steps: int,
    device: str | torch.device | None = None,
    seed: int = 0,
    max_abs_state: float | None = None,
    trajectory_filter: Callable[[torch.Tensor, torch.Tensor], torch.Tensor]
    | None = None,
    log: Callable[[str], None] | None = _nerd_log,
) -> NeRDDataset:
    """Collect a distributed shard of teacher trajectories from any NeRD problem.

    Inputs may be global per world or aligned with the entities in the
    encoded state. Their shape is inferred from the first frame and must remain
    fixed, while their values may vary freely by trajectory and frame. When
    ``device`` is omitted, collection follows the Newton state or active
    distributed rank.

    Trajectories are produced one full world batch (``problem.batch_size`` =
    ``codec.world_count``) at a time per rank, so the effective per-rank count is
    rounded up to a multiple of that batch size and a small surplus from the
    final rollout may be discarded (the surplus simulation compute is inherent to
    Newton's vectorized batched stepping and is not separable). Size
    ``num_trajectories`` so the per-rank target is a multiple of the codec batch
    size to avoid any discard. The returned dataset metadata reports
    ``rejected_trajectory_count``: the measured number of rollouts that the
    finiteness/``max_abs_state``/``trajectory_filter`` checks discarded.
    """
    if num_trajectories <= 0 or steps <= 0:
        raise ValueError("num_trajectories and steps must be positive")
    torch_device = resolve_device(device) if device is not None else None
    rank, world_size = _rank_world_size()
    if num_trajectories < world_size:
        raise ValueError(
            f"num_trajectories ({num_trajectories}) must be at least the "
            f"distributed world size ({world_size})"
        )
    base, remainder = divmod(num_trajectories, world_size)
    local_target = base + int(rank < remainder)
    rng = np.random.default_rng(seed + rank * 1_000_003)
    state_batches: list[torch.Tensor] = []
    input_batches: list[torch.Tensor] = []
    collected = 0
    rejected = 0
    sampled_input_shape: tuple[int, ...] | None = None
    external_input_shape: tuple[int, ...] | None = None

    while collected < local_target:
        problem.reset(rng)
        initial = problem.codec.read(problem.get_state())
        if torch_device is None:
            torch_device = resolve_device(initial.device)
        snapshots = [initial.to(torch_device, dtype=torch.float32).detach().clone()]
        inputs = []
        for frame in range(steps):
            if problem.sample_inputs is None:
                frame_inputs = torch.empty(
                    (problem.batch_size, 0), device=torch_device, dtype=torch.float32
                )
            else:
                frame_inputs = torch.as_tensor(
                    problem.sample_inputs(rng, problem.batch_size, frame),
                    device=torch_device,
                    dtype=torch.float32,
                )
                if frame_inputs.ndim < 2 or frame_inputs.shape[0] != problem.batch_size:
                    raise ValueError(
                        "sample_inputs must return shape "
                        "[problem.batch_size, *external_input_shape]"
                    )
            if sampled_input_shape is None:
                sampled_input_shape = tuple(frame_inputs.shape[1:])
            elif tuple(frame_inputs.shape[1:]) != sampled_input_shape:
                raise ValueError(
                    "sample_inputs must return a consistent shape; "
                    f"expected {sampled_input_shape}, "
                    f"got {tuple(frame_inputs.shape[1:])}"
                )
            model_inputs = (
                frame_inputs
                if problem.observe_inputs is None
                else torch.as_tensor(
                    problem.observe_inputs(frame_inputs, frame),
                    device=torch_device,
                    dtype=torch.float32,
                )
            )
            if model_inputs.ndim < 2 or model_inputs.shape[0] != problem.batch_size:
                raise ValueError(
                    "observe_inputs must return shape "
                    "[problem.batch_size, *external_input_shape]"
                )
            if external_input_shape is None:
                external_input_shape = tuple(model_inputs.shape[1:])
            elif tuple(model_inputs.shape[1:]) != external_input_shape:
                raise ValueError(
                    "collected model inputs must have a consistent shape; "
                    f"expected {external_input_shape}, "
                    f"got {tuple(model_inputs.shape[1:])}"
                )
            inputs.append(model_inputs.detach().clone())
            problem.advance(frame_inputs, frame)
            snapshots.append(
                problem.codec.read(problem.get_state())
                .to(torch_device, dtype=torch.float32)
                .detach()
                .clone()
            )

        states = torch.stack(tuple(snapshots), dim=1)
        input_tensor = torch.stack(tuple(inputs), dim=1)
        valid = torch.isfinite(states).flatten(start_dim=1).all(dim=1)
        valid &= torch.isfinite(input_tensor).flatten(start_dim=1).all(dim=1)
        if max_abs_state is not None:
            valid &= states.abs().flatten(start_dim=1).amax(dim=1) < max_abs_state
        if trajectory_filter is not None:
            custom = torch.as_tensor(
                trajectory_filter(states, input_tensor), device=valid.device
            )
            if custom.shape != valid.shape:
                raise ValueError(
                    "trajectory_filter must return shape "
                    f"{tuple(valid.shape)}, got {tuple(custom.shape)}"
                )
            valid &= custom.bool()
        rejected += int((~valid).sum())
        states, input_tensor = states[valid], input_tensor[valid]
        if states.shape[0] == 0:
            raise RuntimeError(
                "every collected trajectory was rejected; narrow the reset or "
                "inputs distribution"
            )
        take = min(local_target - collected, states.shape[0])
        state_batches.append(states[:take])
        input_batches.append(input_tensor[:take])
        collected += take
        if rank == 0 and log is not None:
            suffix = " on rank 0" if world_size > 1 else ""
            log(f"collected {collected}/{local_target} trajectories{suffix}")

    if torch_device is None:
        raise RuntimeError("trajectory collection did not resolve a device")
    # Each rank stops exactly at its share, so the kept count is always
    # num_trajectories. Report instead the measured number of rollouts that
    # were generated and then discarded by the validity/abs-state/custom
    # filters, which does carry information across runs.
    rejected_count = torch.tensor(rejected, device=torch_device, dtype=torch.int64)
    _all_reduce(rejected_count)
    return NeRDDataset(
        states=torch.cat(tuple(state_batches), dim=0),
        inputs=torch.cat(tuple(input_batches), dim=0),
        codec=problem.codec,
        frame_dt=problem.frame_dt,
        metadata={
            "requested_trajectory_count": num_trajectories,
            "rejected_trajectory_count": int(rejected_count),
            "distributed_world_size": world_size,
            "frames_per_trajectory": steps,
        },
    )
